---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "client/src/**/*"
  - "server/src/**/*"
  - "**/package.json"
  - "**/README.md"
  - "**/CHANGELOG.md"
exclude_paths:
  - "**/node_modules/**/*"
  - "**/out/**/*"
  - "client/server/**/*"
  - "**/.git/**/*"
  - "**/webpack.config.js"
  - "**/tsconfig.json"
  - "**/customInstallServerIntoExtension.js"
  - "**/tsconfig.base.json"
  - "**/shared.webpack.config.js"

