name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: sudo apt install -yqq xvfb
      if: runner.os == 'Linux'
    - uses: actions/checkout@v3
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint --if-present
    - run: npm run compile --if-present
    - run: xvfb-run "--server-args=-screen 0 1024x768x24" -a npm test
      if: runner.os == 'Linux'
      env:
        DBUS_SESSION_BUS_ADDRESS: /dev/null
    - run: npm test
      if: runner.os != 'Linux'
