name: Deploy

# Controls when the action will run.
on:
  push:
    tags:
    - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - name: Publish to Open VSX Registry
      uses: HaaLeo/publish-vscode-extension@v0
      id: publishToOpenVSX
      with:
        pat: ${{ secrets.OPEN_VSX_TOKEN }}
    - name: Publish to Visual Studio Marketplace
      uses: HaaLeo/publish-vscode-extension@v0
      with:
        pat: ${{ secrets.VSCE_TOKEN }}
        registryUrl: https://marketplace.visualstudio.com
        extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
        packagePath: ''
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
