name: Deploy

# Controls when the action will run.
on:
  push:
    tags:
    - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - uses: lannonbr/vsce-action@master
      with:
        args: "package"
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: "*.vsix"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to VS Code Marketplace
      uses: lannonbr/vsce-action@master
      with:
        args: "publish"
      env:
        VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
